services:
   server:
      build:
        context: .
      user: "1000:1000"
      ports:
        - 6060:6060
      volumes:
        - /home/nc/docker/tasky:/database
        - /home/nc/media/video songs:/videos
